# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steem Powered Betting Exchange
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Betsteem is a betting exchange powered by the Steem blockchain, it allows users to bet against each other using their Steem voting power
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://betsteem.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
